### ISSUE TITLE
[Bug] Hamburger icon in navbar is not collapsing right for mobile devices

### ISSUE THREAD

**Issue by jithindasad** [rmsubekti/nangka#1]
**Description**
Navbar is not fully responsive to mobile devices.

**Screenshots**
![Screenshot 2020-10-03 at 10 43 52 PM](https://user-images.githubusercontent.com/26083775/94997807-2e680100-05cb-11eb-8fb3-2d55f3291262.png)

**Solution**
Adding `z-index: 1;` for `.site-nav` class will fix the problem.

**Comment by rmsubekti** [comment]
@jithindasad thanks for your solution, it's already fixed now

**Comment by jithindasad** [comment]
@rmsubekti  Glad to know It's fixed! Good work on the template. It's so minimal. 💯
