### ISSUE TITLE
There is a parsing error when using double quotation in search.json file

### ISSUE THREAD

**Issue by daniel-hebn** [rmsubekti/nangka#3]
When new blog posting include double quotation ( " ) was created, there is parsing error in **search.json**.

For example, when using Java code, quotes can cause errors.
=> System.out.println("json parsing error. because double quotation")

I am suggesting a correction of **search.json's desc property** carefully.

before
{
  		"title"    : "{{ post.title | escape }}",
  		"category" : "{{ post.categories }}",
    	        "desc"     : "{{ post.content | strip_html | strip_newlines | truncate: 200 }}",
                ...
}

after
{
  		"title"    : "{{ post.title | escape }}",
  		"category" : "{{ post.categories }}",
    	        "desc"     : "{{ post.content.replace(/"/gi, "\"") | strip_html | strip_newlines | truncate: 200 }}",
                ...
}

**Comment by rmsubekti** [comment]
thanks @daniel-hebn, 
It might be better to use an `escape` 
```
"desc"     : "{{ post.content | strip_html | strip_newlines | truncate: 200 | escape }}",
```
or `replace` string filter in liquid.
```
"desc"     : "{{ post.content | strip_html | strip_newlines | truncate: 200 | replace: '"','”' }}",
```
If you are satisfied with the solution please close this issue.
😄
